### ISSUE TITLE
KittiMOTS detection file does not have rle 

### ISSUE THREAD

**Issue by chansunsong** [ocetintas/MPNTrackSeg#1]
Hi. Ocentintas 
 Thank you for your great work in MOTS.
I have a question about KittiMOTS detection file.
when I run the code python scripts/train.py with KittiMOTS datasets.
I got this error.
ValueError: Length mismatch: Expected axis has 9 elements, new values have 10 elements
I check Kittiloader code and I realize column has 'rle' which is related to mask but detection file which is dowloaded with yours does not have mask representations.
How can I train KITTI MOTS?

**Comment by ocetintas** [comment]
Thanks for pointing this out, I've updated the KITTI loader. Now, you will not encounter this error with the latest version of the code.
